### ISSUE TITLE
Missing folder and files /push_admin/push_msg/instanceapp

### ISSUE THREAD

**Issue by gpronet** [HMS-Core/hms-push-serverdemo-php#10]
Maybe I am a newb, but I can't locate that folder and the files in it and getting errors as a result:

/push_admin/push_msg/instanceapp/InstanceAppConfig.php
/push_admin/push_msg/instanceapp/InstanceAppPushbody.php
/push_admin/push_msg/instanceapp/InstanceAppRingtone.php

Where do you find those files or do you generate them somehow?

**Comment by Xuejiao-Shi** [comment]
Is this error reported after you perform any other operation, or is this error reported just run the demo? please provide complete error information and logs, and how can we reproduce the problem scene.

**Comment by gpronet** [comment]
I figured it out. In the demo example you have outdated folder/script names in the file /push_common/test_sample_push_msg_common.php.

include_once (dirname(__FILE__) . '/../../push_admin/push_msg/instanceapp/InstanceAppConfig.php');
include_once (dirname(__FILE__) . '/../../push_admin/push_msg/instanceapp/InstanceAppPushbody.php');
include_once (dirname(__FILE__) . '/../../push_admin/push_msg/instanceapp/InstanceAppRingtone.php');

You need to change those lines to the following:

include_once (dirname(__FILE__) . '/../../push_admin/push_msg/quickapp/QuickAppConfig.php');
include_once (dirname(__FILE__) . '/../../push_admin/push_msg/quickapp/QuickAppPushbody.php');
include_once (dirname(__FILE__) . '/../../push_admin/push_msg/quickapp/QuickAppRingtone.php');

Everything works fine then.
