### ISSUE TITLE
minor fixes on unix environment

### ISSUE THREAD

**Issue by RadekSip** [HMS-Core/hms-push-serverdemo-php#2]
Hello,
I'm not PHP developer, I'm only able to modify and use foreign code :-) For this reason I will not send pull request :-)

There were problems with carriage return "%0D" char in $appid and $appsecret (probably caused by windows CRLF vs unix LF?)

`url_https_post curl send body:grant_type=client_credentials&client_secret=blabla123blabla%0D&client_id=123456%0D`

Solution in is `trim()` before usage.
Without this fix, the refresh token failed, result was null

Second problem:
it does not worked, it was not able to find and create instance of class TestPushMsgCommon()
`include_once (dirname(__FILE__) . './push_common/test_sample_push_msg_common.php');`
it works after change to:
`include_once (dirname(__FILE__) . '/push_common/test_sample_push_msg_common.php');`

environment:
Linux & PHP 5.2, macOS & PHP 7.1

**Comment by Mike-mei** [comment]
Hello, we have updated the code  b243ffc to fix this issue,  please try again.
